name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: mstksg/setup-stack@v1
    - uses: actions/cache@v1
      name: Cache ~/.stack
      with:
        path: ~/.stack
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        key: ${{ runner.os }}-stack-${{ hashFiles('stack.yaml') }}
        restore-keys: |
          ${{ runner.os }}-stack-
    - uses: actions/cache@v1
      name: Cache .stack-work
      with:
        path: .stack-work
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        key: ${{ runner.os }}-stack-work-${{ hashFiles('stack.yaml') }}-${{ hashFiles('**/*.hs') }}
        restore-keys: |
          ${{ runner.os }}-stack-work-
    - name: Compile with Stack
      run: stack test
